### ISSUE TITLE
Is there going to be an updated release of ISO images anytime soon?

### ISSUE THREAD

**Issue by TheAlienDrew** [marcosfad/mbp-ubuntu#37]
Just curious, since the last builds were over a year ago.

**Comment by marcosfad** [comment]
Hi, sorry for taking so long to reply. I've been a little bit out of this project in the last months. I'll try to compile a new kernel and image in the coming weeks. Several of the automations are not working due to the size of the project releases. I'm looking for solutions.
You are going to have new latest next Sunday.
