### ISSUE TITLE
snd_hda_macbookpro module iMac 19,1

### ISSUE THREAD

**Issue by lui75** [marcosfad/mbp-ubuntu#88]
Hi, why don't you add davidjo patches to your kernel for enabling audio on macbook pro and iMac? I have tried to build and install the modules but the lack of linux-source deb package for your kernel makes it impossible. So, now my wifi is working perfectly but I can not have audio working
Here's the repository: https://github.com/davidjo/snd_hda_macbookpro

**Comment by AdityaGarg8** [comment]
In line 84 and 87 of https://github.com/davidjo/snd_hda_macbookpro/blob/master/install.cirrus.driver.sh, change `isubuntu=1` to `isubuntu=0` and run the script again.

In case you still face issues, then we can try adding the driver to the kernel, but you’ll have to be a tester since we mainly deal with t2 macs.

**Comment by lui75** [comment]
I got this message from T2 Ubuntu kernel:
https://github.com/t2linux/T2-Ubuntu/issues/88#issuecomment-1553479103

**Comment by lui75** [comment]
It worked flawlessly! If you decide to add the driver into the kernel, I will be a tester. Let me know what I have to do and how. I am happy to be of help.

**Comment by AdityaGarg8** [comment]
If that works then good. Still if you need it in the kernel, reopen this issue.

Also, in case you are using the T2 kernels, make sure the kernel upgrade script is set up to receive the updates.

https://github.com/t2linux/T2-Ubuntu-Kernel#using-the-kernel-upgrade-script
